"""Initial migration

Revision ID: 1b3d94bcc2ff
Revises: 
Create Date: 2024-04-22 17:23:04.724972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3d94bcc2ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objectID', sa.Integer(), nullable=False),
    sa.Column('isHighlight', sa.Boolean(), nullable=True),
    sa.Column('accessionNumber', sa.String(length=255), nullable=True),
    sa.Column('accessionYear', sa.String(length=255), nullable=True),
    sa.Column('isPublicDomain', sa.Boolean(), nullable=True),
    sa.Column('primaryImage', sa.String(length=255), nullable=True),
    sa.Column('primaryImageSmall', sa.String(length=255), nullable=True),
    sa.Column('additionalImages', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('objectName', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('artistName', sa.String(length=255), nullable=True),
    sa.Column('artistNationality', sa.String(length=255), nullable=True),
    sa.Column('artistBeginDate', sa.String(length=255), nullable=True),
    sa.Column('artistEndDate', sa.String(length=255), nullable=True),
    sa.Column('artistWikidataURL', sa.String(length=255), nullable=True),
    sa.Column('artistUlanURL', sa.String(length=255), nullable=True),
    sa.Column('medium', sa.String(length=255), nullable=True),
    sa.Column('dimensions', sa.Text(), nullable=True),
    sa.Column('galleryNumber', sa.String(length=255), nullable=True),
    sa.Column('classification', sa.String(length=255), nullable=True),
    sa.Column('repository', sa.String(length=255), nullable=True),
    sa.Column('objectURL', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artwork')),
    sa.UniqueConstraint('objectID', name=op.f('uq_artwork_objectID'))
    )
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artwork_galleryNumber'), ['galleryNumber'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email_address', name=op.f('uq_user_email_address')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('to_view',
    sa.Column('objectId', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.id'], name=op.f('fk_to_view_artwork_id_artwork')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_to_view_user_id_user')),
    sa.PrimaryKeyConstraint('objectId', name=op.f('pk_to_view'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_view')
    op.drop_table('user')
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artwork_galleryNumber'))

    op.drop_table('artwork')
    # ### end Alembic commands ###
