"""Updated foreign key to use objectID

Revision ID: 3fa50a1b6388
Revises: 83ade678daf8
Create Date: 2024-04-30 10:45:31.517317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa50a1b6388'
down_revision = '83ade678daf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artwork_objectID', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_to_view_artwork_id_artwork', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_to_view_artwork_objectID_artwork'), 'artwork', ['artwork_objectID'], ['objectID'])
        batch_op.drop_column('artwork_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artwork_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_to_view_artwork_objectID_artwork'), type_='foreignkey')
        batch_op.create_foreign_key('fk_to_view_artwork_id_artwork', 'artwork', ['artwork_id'], ['id'])
        batch_op.drop_column('artwork_objectID')

    # ### end Alembic commands ###
