"""Initial migration.

Revision ID: 450e1c8ddff2
Revises: 
Create Date: 2024-04-21 11:44:50.217708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450e1c8ddff2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('artistID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('beginDate', sa.String(length=120), nullable=True),
    sa.Column('endDate', sa.String(length=120), nullable=True),
    sa.Column('wikidataURL', sa.String(length=255), nullable=True),
    sa.Column('ulanURL', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('artistID')
    )
    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objectID', sa.Integer(), nullable=False),
    sa.Column('isHighlight', sa.Boolean(), nullable=True),
    sa.Column('accessionNumber', sa.String(length=120), nullable=True),
    sa.Column('accessionYear', sa.String(length=120), nullable=True),
    sa.Column('isPublicDomain', sa.Boolean(), nullable=True),
    sa.Column('primaryImage', sa.String(length=255), nullable=True),
    sa.Column('primaryImageSmall', sa.String(length=255), nullable=True),
    sa.Column('additionalImages', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('objectName', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('artistID', sa.Integer(), nullable=True),
    sa.Column('medium', sa.String(length=255), nullable=True),
    sa.Column('dimensions', sa.Text(), nullable=True),
    sa.Column('galleryNumber', sa.String(length=120), nullable=True),
    sa.Column('classification', sa.String(length=255), nullable=True),
    sa.Column('repository', sa.String(length=255), nullable=True),
    sa.Column('objectURL', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artistID'], ['artist.artistID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objectID')
    )
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artwork_galleryNumber'), ['galleryNumber'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artwork_galleryNumber'))

    op.drop_table('artwork')
    op.drop_table('artist')
    # ### end Alembic commands ###
