"""Update relationships

Revision ID: 7d9765c89d64
Revises: d691dd332222
Create Date: 2024-05-03 15:55:59.410250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9765c89d64'
down_revision = 'd691dd332222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_artworks', schema=None) as batch_op:
        batch_op.drop_column('galleryNumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('galleryNumber', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
