"""empty message

Revision ID: 83ade678daf8
Revises: f664f9858815
Create Date: 2024-04-25 10:53:22.432679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ade678daf8'
down_revision = 'f664f9858815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artistDisplayName', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('artistDisplayBio', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('objectDate', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('objectDate')
        batch_op.drop_column('artistDisplayBio')
        batch_op.drop_column('artistDisplayName')

    # ### end Alembic commands ###
