"""added Collections and Collections_Artworks tables

Revision ID: d691dd332222
Revises: 3fa50a1b6388
Create Date: 2024-05-03 15:36:29.965168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd691dd332222'
down_revision = '3fa50a1b6388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_collection_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection'))
    )
    op.create_table('collection_artworks',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('galleryNumber', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.objectID'], name=op.f('fk_collection_artworks_artwork_id_artwork')),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_collection_artworks_collection_id_collection')),
    sa.PrimaryKeyConstraint('collection_id', 'artwork_id', name=op.f('pk_collection_artworks'))
    )
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('repository')
        batch_op.drop_column('additionalImages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additionalImages', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('repository', sa.VARCHAR(length=255), nullable=True))

    op.drop_table('collection_artworks')
    op.drop_table('collection')
    # ### end Alembic commands ###
